tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: EDW_DB
      schema: dev
      warehouse: DBT_WH
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: EDW_DB
      schema: prod
      warehouse: DBT_WH