tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: ANB_APP
      schema: DEV
      warehouse: dbt_dev_wh
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: ANB_APP
      schema: prod
      warehouse: dbt_dev_wh